apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-morpheus-client
  labels:
    app: agent-morpheus-client
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus-client
  template:
    metadata:
      labels:
        app: agent-morpheus-client
    spec:
      containers:
        - name: agent-morpheus-client
          image: quay.io/ecosystem-appeng/agent-morpheus-client:latest
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: QUARKUS_REST-CLIENT_MORPHEUS_URL
              value: http://agent-morpheus-rh:8080/scan
            - name: MORPHEUS_REPORTS_PATH
              value: /data
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: agent-morpheus-client-data
---
apiVersion: v1
kind: Service
metadata:
  name: agent-morpheus-client
  labels:
    app: agent-morpheus-client
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: agent-morpheus-client
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: agent-morpheus-client
spec:
  port:
    targetPort: 8080 
  to:
    kind: Service
    name: agent-morpheus-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-morpheus-client-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
